### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by ChrisBono** [vvcephei/es-client-java#17]
Currently when we get an exception in the ES call, we get back an exception that is not that helpful.

org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution
    cause: java.util.concurrent.ExecutionException: java.lang.NullPointerException      

with no stack info. Need to have stack so we know where it occurred.

**Comment by vvcephei** [comment]
I'm looking at the XContentResponseTransform, and I don't see how the exception you've reported could possibly be thrown. Can you provide any more information?

**Comment by vvcephei** [comment]
Specifically, the client never throws an `UncategorizedExecutionException`, only `RuntimeException`.

**Comment by ChrisBono** [comment]
Might be an ES issue. See org.elasticsearch.action.support.AdapterActionFuture
thats where its thrown out of

**Comment by vvcephei** [comment]
The issue was that the search response transform was producing an NPE. Sadly, the futures code swallows the stacktrace, and there's not much we can do about it. Closing for now...
